DROP TABLE IF EXISTS users, items, requests, bookings, comments;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(1000) NOT NULL,
  requester_id BIGINT REFERENCES users (user_id),
  created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (request_id)
);
CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  available BOOLEAN NOT NULL,
  owner BIGINT,
  request_id         BIGINT REFERENCES requests (request_id),
  CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT fk_owner FOREIGN KEY (owner) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS bookings (
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (booking_id),
  CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(item_id),
  CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
  item_id BIGINT NOT NULL,
  author_id VARCHAR(50) NOT NULL,
  created TIMESTAMP NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (comment_id),
  CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items(item_id),
  CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users(user_id)
);